# Translations template for python-fedora.
# Copyright (C) 2007 ORGANIZATION
# This file is distributed under the same license as the python-fedora
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2007.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: python-fedora 0.2.90.22\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2007-12-21 18:01-0700\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9\n"

#: fedora/accounts/fas.py:92
msgid "Authentication config fedora-db-access is not available"
msgstr ""

#: fedora/accounts/fas.py:247
#, python-format
msgid "Username/password mismatch for %(username)s"
msgstr ""

#: fedora/accounts/fas.py:269 fedora/accounts/fas.py:296
#, python-format
msgid "No such user: %(username)s"
msgstr ""

#: fedora/accounts/fas.py:412
msgid "No user set"
msgstr ""

#: fedora/accounts/fas.py:511
#, python-format
msgid "No such user %(user)s"
msgstr ""

#: fedora/accounts/fas.py:539
#, python-format
msgid "No such group: %(group)s"
msgstr ""

#: fedora/accounts/fasLDAP.py:46
msgid "Authentication config file fedora-db-access is not available"
msgstr ""

#: fedora/accounts/fasLDAP.py:256
#, python-format
msgid "User not in group %(group)s"
msgstr ""

#: fedora/accounts/fasLDAP.py:263
#, python-format
msgid "Could Not delete %(username)s from %(group)s"
msgstr ""

#: fedora/accounts/fasLDAP.py:275
msgid "Already in that group"
msgstr ""

#: fedora/accounts/fasLDAP.py:279
#, python-format
msgid "Group \"%(group)s\" does not exist"
msgstr ""

#: fedora/accounts/fasLDAP.py:445 fedora/accounts/fasLDAP.py:459
msgid "User is not approved"
msgstr ""

#: fedora/accounts/fasLDAP.py:447
msgid "User cannot be upgraded beyond administrator"
msgstr ""

#: fedora/accounts/fasLDAP.py:461
msgid "User cannot be downgraded below user, did you mean remove?"
msgstr ""

#: fedora/accounts/util.py:79
#, python-format
msgid "Authentication source \"%(db)s\" not configured"
msgstr ""

#: fedora/tg/client.py:86
msgid "username must be set"
msgstr ""

#: fedora/tg/client.py:88
msgid "password must be set"
msgstr ""

#: fedora/tg/client.py:101
msgid "Invalid username/password"
msgstr ""

#: fedora/tg/client.py:108
#, python-format
msgid "Unable to login to server: %(message)s"
msgstr ""

#: fedora/tg/client.py:116
msgid "Unable to login to the server.  Server did not send back a cookie"
msgstr ""

#: fedora/tg/client.py:153
#, python-format
msgid "Loaded session %(cookie)s"
msgstr ""

#: fedora/tg/client.py:156
#, python-format
msgid "Unable to load session from %(file)s"
msgstr ""

#: fedora/tg/client.py:159
msgid "Session is for a different user"
msgstr ""

#: fedora/tg/client.py:173
#, python-format
msgid "Creating request %(url)s"
msgstr ""

#: fedora/tg/client.py:193
#, python-format
msgid "Unable to log into server: %(error)s"
msgstr ""

#: fedora/tg/client.py:216
#, python-format
msgid "Unable to log into server: %(message)s"
msgstr ""

#: fedora/tg/identity/safas2provider.py:123
#: fedora/tg/identity/safasprovider.py:137
#, python-format
msgid "Loading: %(visitmod)s"
msgstr ""

#: fedora/tg/identity/safas2provider.py:138
#: fedora/tg/identity/safasprovider.py:165
#, python-format
msgid "Passwords do not match for user: %(user)s"
msgstr ""

#: fedora/tg/identity/safas2provider.py:142
#: fedora/tg/identity/safasprovider.py:169
#, python-format
msgid "Login successful for %(user)s"
msgstr ""

#: fedora/tg/identity/safas2provider.py:167
#, python-format
msgid "AccountSystem threw an exception: %(err)s"
msgstr ""

#: fedora/tg/identity/safasprovider.py:161
#: fedora/tg/identity/safasprovider.py:174
#, python-format
msgid "Error %(err)s for %(user)s"
msgstr ""

#: fedora/tg/identity/safasprovider.py:201
#, python-format
msgid "AccountSystem threw an exception: %(err)s for %(user)s"
msgstr ""

